version: "3.1"
services:
  echocloud_db:
    image: mysql
    container_name: echocloud_week
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes: # 挂载
      - ./data/mysql/:/var/lib/mysql
      - ./logs/mysql/:/var/log/mysql
      - ./conf/echocloud-init.d/ec-init.sql:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime
    privileged: true 
    networks:
      - echocloud

  echocloud_redis:
    image: redis:latest
    container_name: echocloud_redis
    command: redis-server /etc/redis/ec-redis.conf
    ports:
      - 6379:6379
    volumes: # 挂载
      - ./conf/echocloud-redis/ec-redis.conf:/etc/redis/ec-redis.conf
      - /etc/localtime:/etc/localtime
    restart: always
    privileged: true 
    networks:
      - echocloud


  echocloudapp:
#    image: cc2c/app-env:v1.0
    image: echocloud-weekreport:v0720
    container_name: echocloudapp
    ports:
      - 31712:31712
    volumes: # 挂载上传文件
      - ./data/uploads/:/usr/local/echoucloud-weekreport/uploads/
      - ./logs/server/:/usr/local/echoucloud-weekreport/logs/
      - ./conf/echocloud-admin-web/:/usr/local/echoucloud-weekreport/
      - /etc/localtime:/etc/localtime

    depends_on:
      - echocloud_db
      - echocloud_redis
    restart: always
    privileged: true
    command: ["/usr/local/echoucloud-weekreport/start.sh"]
    networks:
      - echocloud

  echocloud_nginx:
    image: nginx:latest
    container_name: echocloud_nginx
    ports:
      - 35817:35817  # 暴露端口
    volumes: # 挂载
      - ./conf/saimo-week-repot:/usr/share/nginx/html
      - ./conf/echocloud-nginx/ec-nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime
    restart: always
    privileged: true 
    depends_on:
      - echocloudapp
    networks:
      - echocloud
      

      
networks:
  echocloud:
    driver: bridge
